name: Archive

on:
  push:
    branches: stable
    paths:
      - '.github/workflows/archive.yml'
      - '**/*.swift'
      - 'templates/**'
  pull_request:
    paths:
      - '.github/workflows/archive.yml'
      - '**/*.swift'
      - 'templates/**'

env:
  xcode-version: 12.0.0

jobs:
  install:
    name: Install
    runs-on: macos-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Xcode Select
        uses: devbotsxyz/xcode-select@v1.0.0
        with:
          version: ${{ env.xcode-version }}
      - 
        name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      -
        name: Verify installation
        run: bundle exec rake cli:install[./standalone,./standalone/frameworks,./standalone/stencils]
      -
        name: Check swiftgen binary
        run: |
            ./standalone/swiftgen --version
            ./standalone/swiftgen templates list

  zip:
    name: Zip
    runs-on: macos-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Xcode Select
        uses: devbotsxyz/xcode-select@v1.0.0
        with:
          version: ${{ env.xcode-version }}
      - 
        name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      -
        name: Create zip
        run: bundle exec rake release:zip
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: SwiftGen.zip
          path: build/swiftgen-*.zip
