name: Danger

on:
  push:
    branches: stable
    paths:
      - '.github/workflows/danger.yml'
      - '**/*.swift'
      - 'templates/**'
  pull_request:
    paths:
      - '.github/workflows/danger.yml'
      - '**/*.swift'
      - 'templates/**'

env:
  xcode-version: 12.0.0

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      -
        name: Run Danger
        run: bundle exec danger --verbose
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.danger_github_api_token }}
